export enum UserRole { OWNER = 'OWNER', ADMIN = 'ADMIN', STAFF = 'STAFF', TENANT = 'TENANT' }
export enum Gender { MALE = 'MALE', FEMALE = 'FEMALE', OTHER = 'OTHER' }
export enum RoomStatus { AVAILABLE = 'AVAILABLE', RESERVED = 'RESERVED', OCCUPIED = 'OCCUPIED', MAINTENANCE = 'MAINTENANCE', INACTIVE = 'INACTIVE' }
export enum PricingTerm { DAILY = 'DAILY', WEEKLY = 'WEEKLY', BIWEEKLY = 'BIWEEKLY', MONTHLY = 'MONTHLY', SMESTERLY = 'SMESTERLY', YEARLY = 'YEARLY' }
export enum StayStatus { ACTIVE = 'ACTIVE', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED' }
export enum DepositStatus { HELD = 'HELD', PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED', REFUNDED = 'REFUNDED', FORFEITED = 'FORFEITED' }
export enum UtilityType { ELECTRICITY = 'ELECTRICITY', WATER = 'WATER' }
export enum InvoiceStatus { DRAFT = 'DRAFT', ISSUED = 'ISSUED', PARTIAL = 'PARTIAL', PAID = 'PAID', CANCELLED = 'CANCELLED' }
export enum InvoiceLineType { RENT = 'RENT', ELECTRICITY = 'ELECTRICITY', WATER = 'WATER', PENALTY = 'PENALTY', DISCOUNT = 'DISCOUNT', WIFI = 'WIFI', OTHER = 'OTHER' }
export enum PaymentMethod { CASH = 'CASH', TRANSFER = 'TRANSFER', QRIS = 'QRIS', EWALLET = 'EWALLET', OTHER = 'OTHER' }
export enum TicketStatus { OPEN = 'OPEN', IN_PROGRESS = 'IN_PROGRESS', DONE = 'DONE', CLOSED = 'CLOSED', CANCELLED = 'CANCELLED' }
export enum TicketCategory { KEBERSIHAN = 'KEBERSIHAN', PERBAIKAN = 'PERBAIKAN', AUDIT_INVENTARIS = 'AUDIT_INVENTARIS', BARANG_PINDAH = 'BARANG_PINDAH', PEMERIKSAAN = 'PEMERIKSAAN', UMUM = 'UMUM', BARANG_RUSAK = 'BARANG_RUSAK', CEK_KAMAR = 'CEK_KAMAR', STOK_HABIS = 'STOK_HABIS', CATATAN_METER = 'CATATAN_METER', CLEANING = 'CLEANING', ELECTRICITY = 'ELECTRICITY', PLUMBING = 'PLUMBING', AC = 'AC', WIFI = 'WIFI', DOOR_KEY = 'DOOR_KEY', FURNITURE = 'FURNITURE', PEST = 'PEST', SECURITY = 'SECURITY', NOISE = 'NOISE', CHECKIN_CHECKOUT = 'CHECKIN_CHECKOUT', PAYMENT_ADMIN = 'PAYMENT_ADMIN', EMERGENCY = 'EMERGENCY', GENERAL = 'GENERAL', OTHER = 'OTHER', CHECKOUT_INSPECTION = 'CHECKOUT_INSPECTION', ROOM_REPAIR = 'ROOM_REPAIR' }
export const BACKOFFICE_TICKET_CATEGORIES = [TicketCategory.KEBERSIHAN, TicketCategory.PERBAIKAN, TicketCategory.AUDIT_INVENTARIS, TicketCategory.BARANG_PINDAH, TicketCategory.PEMERIKSAAN, TicketCategory.UMUM] as const;
export const STAFF_FIELD_CATEGORY_SET = new Set([TicketCategory.BARANG_RUSAK, TicketCategory.CEK_KAMAR, TicketCategory.STOK_HABIS, TicketCategory.PERBAIKAN, TicketCategory.CATATAN_METER, TicketCategory.KEBERSIHAN]);
export enum RoomItemStatus { GOOD = 'GOOD', DAMAGED = 'DAMAGED', MAINTENANCE = 'MAINTENANCE', MISSING = 'MISSING' }
export enum InventoryItemStatus { GOOD = 'GOOD', LOW_STOCK = 'LOW_STOCK', OUT_OF_STOCK = 'OUT_OF_STOCK', DAMAGED = 'DAMAGED', MISSING = 'MISSING', NEEDS_REPAIR = 'NEEDS_REPAIR', PENDING_CHECK = 'PENDING_CHECK' }
export enum ReportedCondition { DAMAGED = 'DAMAGED', MISSING = 'MISSING', NEEDS_REPAIR = 'NEEDS_REPAIR', NEEDS_REPLACEMENT = 'NEEDS_REPLACEMENT', NEEDS_CLEANING = 'NEEDS_CLEANING', LOW_STOCK = 'LOW_STOCK', OUT_OF_STOCK = 'OUT_OF_STOCK', PENDING_CHECK = 'PENDING_CHECK' }
export enum AdminDecision { APPROVE = 'APPROVE', REJECT = 'REJECT', NEEDS_MORE_INFO = 'NEEDS_MORE_INFO' }
export enum StaffFieldReportStatus { REPORTED = 'REPORTED', UNDER_REVIEW = 'UNDER_REVIEW', APPROVED = 'APPROVED', REJECTED = 'REJECTED', IN_REPAIR = 'IN_REPAIR', DONE = 'DONE', CLOSED = 'CLOSED' }
export enum InventoryMovementType { IN = 'IN', OUT = 'OUT', ASSIGN_TO_ROOM = 'ASSIGN_TO_ROOM', RETURN_FROM_ROOM = 'RETURN_FROM_ROOM', ADJUSTMENT = 'ADJUSTMENT' }
export enum AnnouncementAudience { TENANT = 'TENANT', ALL = 'ALL' }
export enum LeadSource { GOOGLE_MAPS = 'GOOGLE_MAPS', WALK_IN = 'WALK_IN', REFERRAL = 'REFERRAL', INSTAGRAM = 'INSTAGRAM', TIKTOK = 'TIKTOK', WHATSAPP = 'WHATSAPP', FACEBOOK = 'FACEBOOK', WEBSITE = 'WEBSITE', OTA = 'OTA', OTHER = 'OTHER' }
export enum StayPurpose { WORK = 'WORK', STUDY = 'STUDY', TRANSIT = 'TRANSIT', FAMILY = 'FAMILY', MEDICAL = 'MEDICAL', PROJECT = 'PROJECT', OTHER = 'OTHER' }
export enum ExpenseType { FIXED = 'FIXED', VARIABLE = 'VARIABLE' }
export enum ExpenseCategory { RENT_BUILDING = 'RENT_BUILDING', SALARY = 'SALARY', ELECTRICITY = 'ELECTRICITY', WATER = 'WATER', INTERNET = 'INTERNET', MAINTENANCE = 'MAINTENANCE', CLEANING = 'CLEANING', SUPPLIES = 'SUPPLIES', TAX = 'TAX', MARKETING = 'MARKETING', OTHER = 'OTHER' }

export enum PaymentSubmissionStatus { PENDING_REVIEW = 'PENDING_REVIEW', APPROVED = 'APPROVED', REJECTED = 'REJECTED', EXPIRED = 'EXPIRED' }

export enum PaymentSubmissionTargetType { INVOICE = 'INVOICE', DEPOSIT = 'DEPOSIT' }
export enum BookingDepositPaymentStatus { UNPAID = 'UNPAID', PARTIAL = 'PARTIAL', PAID = 'PAID' }

export enum TenantDepositLedgerEntryType { CHARGED = 'CHARGED', PAYMENT_RECEIVED = 'PAYMENT_RECEIVED', HELD = 'HELD', REFUND = 'REFUND', DEDUCTION = 'DEDUCTION', FORFEIT = 'FORFEIT', SETTLEMENT = 'SETTLEMENT', ADJUSTMENT = 'ADJUSTMENT', MIGRATION_SNAPSHOT = 'MIGRATION_SNAPSHOT' }
export enum TenantDepositLedgerDirection { INCREASE_LIABILITY = 'INCREASE_LIABILITY', DECREASE_LIABILITY = 'DECREASE_LIABILITY', INFO = 'INFO' }

export enum RenewRequestStatus { PENDING = 'PENDING', APPROVED = 'APPROVED', REJECTED = 'REJECTED', PENDING_DECISION = 'PENDING_DECISION', AWAITING_DP = 'AWAITING_DP', DP_SECURED = 'DP_SECURED', COMPLETED = 'COMPLETED', REJECTED_BY_TENANT = 'REJECTED_BY_TENANT', EXPIRED_PRIORITY = 'EXPIRED_PRIORITY', FORFEITED = 'FORFEITED' }

export enum CheckoutRequestStatus { PENDING = 'PENDING', APPROVED = 'APPROVED', REJECTED = 'REJECTED' }
export enum StaffRoutineFrequency { DAILY = 'DAILY', WEEKLY = 'WEEKLY', MONTHLY = 'MONTHLY' }
export enum StaffRoutineAreaType { GENERAL = 'GENERAL', BATHROOM = 'BATHROOM', ROOM = 'ROOM', INVENTORY = 'INVENTORY', METER = 'METER', SECURITY = 'SECURITY', CLEANING = 'CLEANING' }
export enum StaffRoutineStatus { IN_PROGRESS = 'IN_PROGRESS', DONE = 'DONE', NEED_HELP = 'NEED_HELP', MISSED = 'MISSED', SKIPPED = 'SKIPPED' }

export enum StaffWorkSourceType { ROUTINE = 'ROUTINE', TICKET = 'TICKET', METER = 'METER', ROOM_CHECK = 'ROOM_CHECK', STOCK_REPORT = 'STOCK_REPORT', INVENTORY_REPORT = 'INVENTORY_REPORT', TENANT_REVIEW = 'TENANT_REVIEW', MANUAL_AUDIT = 'MANUAL_AUDIT' }
export enum StaffAuditResult { PASS = 'PASS', NEEDS_FIX = 'NEEDS_FIX', FAILED = 'FAILED', NOT_DONE = 'NOT_DONE' }
export enum StaffReviewStatus { VISIBLE = 'VISIBLE', HIDDEN = 'HIDDEN', FLAGGED = 'FLAGGED' }
export enum StaffPerformanceEventType { ROUTINE_DONE = 'ROUTINE_DONE', ROUTINE_NEED_HELP = 'ROUTINE_NEED_HELP', TICKET_DONE = 'TICKET_DONE', METER_RECORDED = 'METER_RECORDED', STOCK_REPORTED = 'STOCK_REPORTED', AUDIT_PASS = 'AUDIT_PASS', AUDIT_NEEDS_FIX = 'AUDIT_NEEDS_FIX', AUDIT_FAILED = 'AUDIT_FAILED', TENANT_REVIEW_HIGH = 'TENANT_REVIEW_HIGH', TENANT_REVIEW_LOW = 'TENANT_REVIEW_LOW', MISSING_PROOF = 'MISSING_PROOF', MANUAL_ADJUSTMENT = 'MANUAL_ADJUSTMENT' }

export enum FixedAssetCategory { BUILDING = 'BUILDING', RENOVATION = 'RENOVATION', ROOM_EQUIPMENT = 'ROOM_EQUIPMENT', FURNITURE = 'FURNITURE', ELECTRONIC = 'ELECTRONIC', UTILITY_EQUIPMENT = 'UTILITY_EQUIPMENT', VEHICLE = 'VEHICLE', SOFTWARE = 'SOFTWARE', OTHER = 'OTHER' }
export enum FixedAssetStatus { DRAFT = 'DRAFT', ACTIVE = 'ACTIVE', FULLY_DEPRECIATED = 'FULLY_DEPRECIATED', DISPOSED = 'DISPOSED', WRITTEN_OFF = 'WRITTEN_OFF' }
export enum FixedAssetLocationType { GENERAL = 'GENERAL', ROOM = 'ROOM', WAREHOUSE = 'WAREHOUSE' }
export enum FixedAssetCapitalizationSource { OPENING_BALANCE = 'OPENING_BALANCE', PURCHASE_JOURNAL = 'PURCHASE_JOURNAL', DISCLOSURE_ONLY = 'DISCLOSURE_ONLY' }
export enum FixedAssetDepreciationMethod { STRAIGHT_LINE = 'STRAIGHT_LINE' }
export enum FixedAssetLedgerAlignmentStatus { NOT_REQUIRED = 'NOT_REQUIRED', NEEDS_REVIEW = 'NEEDS_REVIEW', PREVIEWED = 'PREVIEWED', ALIGNED = 'ALIGNED', DISCLOSURE_ONLY = 'DISCLOSURE_ONLY', VOIDED = 'VOIDED' }
export enum FixedAssetLedgerAlignmentMethod { RECLASSIFY_FROM_CASH = 'RECLASSIFY_FROM_CASH', OWNER_CAPITAL_CONTRIBUTION = 'OWNER_CAPITAL_CONTRIBUTION', DISCLOSURE_ONLY = 'DISCLOSURE_ONLY', MANUAL_REVIEW = 'MANUAL_REVIEW' }
export enum AssetDepreciationRunStatus { POSTED = 'POSTED', VOID = 'VOID' }