export enum UserRole { OWNER = 'OWNER', ADMIN = 'ADMIN', STAFF = 'STAFF', TENANT = 'TENANT' }
export enum Gender { MALE = 'MALE', FEMALE = 'FEMALE', OTHER = 'OTHER' }
export enum RoomStatus { AVAILABLE = 'AVAILABLE', RESERVED = 'RESERVED', OCCUPIED = 'OCCUPIED', MAINTENANCE = 'MAINTENANCE', INACTIVE = 'INACTIVE' }
export enum PricingTerm { DAILY = 'DAILY', WEEKLY = 'WEEKLY', BIWEEKLY = 'BIWEEKLY', MONTHLY = 'MONTHLY', SMESTERLY = 'SMESTERLY', YEARLY = 'YEARLY' }
export enum StayStatus { ACTIVE = 'ACTIVE', COMPLETED = 'COMPLETED', CANCELLED = 'CANCELLED' }
export enum DepositStatus { HELD = 'HELD', PARTIALLY_REFUNDED = 'PARTIALLY_REFUNDED', REFUNDED = 'REFUNDED', FORFEITED = 'FORFEITED' }
export enum UtilityType { ELECTRICITY = 'ELECTRICITY', WATER = 'WATER' }
export enum InvoiceStatus { DRAFT = 'DRAFT', ISSUED = 'ISSUED', PARTIAL = 'PARTIAL', PAID = 'PAID', CANCELLED = 'CANCELLED' }
export enum InvoiceLineType { RENT = 'RENT', ELECTRICITY = 'ELECTRICITY', WATER = 'WATER', PENALTY = 'PENALTY', DISCOUNT = 'DISCOUNT', WIFI = 'WIFI', OTHER = 'OTHER' }
export enum PaymentMethod { CASH = 'CASH', TRANSFER = 'TRANSFER', QRIS = 'QRIS', EWALLET = 'EWALLET', OTHER = 'OTHER' }
export enum TicketStatus { OPEN = 'OPEN', IN_PROGRESS = 'IN_PROGRESS', DONE = 'DONE', CLOSED = 'CLOSED', CANCELLED = 'CANCELLED' }
export enum RoomItemStatus { GOOD = 'GOOD', DAMAGED = 'DAMAGED', MAINTENANCE = 'MAINTENANCE', MISSING = 'MISSING' }
export enum InventoryMovementType { IN = 'IN', OUT = 'OUT', ASSIGN_TO_ROOM = 'ASSIGN_TO_ROOM', RETURN_FROM_ROOM = 'RETURN_FROM_ROOM', ADJUSTMENT = 'ADJUSTMENT' }
export enum AnnouncementAudience { TENANT = 'TENANT', ALL = 'ALL' }
export enum LeadSource { GOOGLE_MAPS = 'GOOGLE_MAPS', WALK_IN = 'WALK_IN', REFERRAL = 'REFERRAL', INSTAGRAM = 'INSTAGRAM', TIKTOK = 'TIKTOK', WHATSAPP = 'WHATSAPP', FACEBOOK = 'FACEBOOK', WEBSITE = 'WEBSITE', OTA = 'OTA', OTHER = 'OTHER' }
export enum StayPurpose { WORK = 'WORK', STUDY = 'STUDY', TRANSIT = 'TRANSIT', FAMILY = 'FAMILY', MEDICAL = 'MEDICAL', PROJECT = 'PROJECT', OTHER = 'OTHER' }
export enum ExpenseType { FIXED = 'FIXED', VARIABLE = 'VARIABLE' }
export enum ExpenseCategory { RENT_BUILDING = 'RENT_BUILDING', SALARY = 'SALARY', ELECTRICITY = 'ELECTRICITY', WATER = 'WATER', INTERNET = 'INTERNET', MAINTENANCE = 'MAINTENANCE', CLEANING = 'CLEANING', SUPPLIES = 'SUPPLIES', TAX = 'TAX', MARKETING = 'MARKETING', OTHER = 'OTHER' }

export enum PaymentSubmissionStatus { PENDING_REVIEW = 'PENDING_REVIEW', APPROVED = 'APPROVED', REJECTED = 'REJECTED', EXPIRED = 'EXPIRED' }

export enum PaymentSubmissionTargetType { INVOICE = 'INVOICE', DEPOSIT = 'DEPOSIT' }
export enum BookingDepositPaymentStatus { UNPAID = 'UNPAID', PARTIAL = 'PARTIAL', PAID = 'PAID' }

export enum RenewRequestStatus { PENDING = 'PENDING', APPROVED = 'APPROVED', REJECTED = 'REJECTED' }
