import { chromium } from 'playwright';
const API = 'http://localhost:3000/api';
const APP = 'http://localhost:5173';
const res = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identifier: 'owner@kost48.com', password: 'Owner#2026' }) });
const token = (await res.json())?.data?.accessToken;
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1280, height: 900 } });
await ctx.addInitScript((t) => window.localStorage.setItem('kost48_access_token', t), token);
const p = await ctx.newPage();
const errs = [];
p.on('pageerror', (e) => errs.push('PAGEERROR: ' + (e.message || e)));
await p.goto(APP + '/rooms/1', { waitUntil: 'networkidle', timeout: 30000 }).catch((e) => errs.push('GOTO ' + e.message));
await p.waitForTimeout(1200);
await p.getByRole('tab', { name: /Meter/i }).click().catch(() => p.getByText(/^Meter/).first().click().catch(() => {}));
await p.waitForTimeout(900);
await p.screenshot({ path: 'ui-shots/meter_tab.png', fullPage: false });
await p.getByRole('button', { name: /Catat & Terbitkan Tagihan/i }).click().catch((e) => errs.push('btn ' + e.message));
await p.waitForTimeout(900);
await p.screenshot({ path: 'ui-shots/meter_cycle_modal.png', fullPage: false });
console.log('ERRORS:', errs.length ? errs.slice(0, 5) : 'none');
await b.close();
