import { chromium } from 'playwright';
const API = 'http://localhost:3000/api', APP = 'http://localhost:5173';
const r = await fetch(`${API}/auth/login`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ identifier: 'maya.tenant@kost48.test', password: 'Tenant#2026' }) });
const token = (await r.json())?.data?.accessToken;
const lb = await (await fetch(`${API}/me/loyalty/leaderboard`, { headers: { Authorization: `Bearer ${token}` } })).json();
console.log('leaderboard:', JSON.stringify(lb.data));
const b = await chromium.launch();
const ctx = await b.newContext({ viewport: { width: 1100, height: 1200 } });
await ctx.addInitScript((t) => window.localStorage.setItem('kost48_access_token', t), token);
const p = await ctx.newPage(); const errs = [];
p.on('pageerror', (e) => errs.push(String(e.message || e)));
await p.goto(APP + '/portal/loyalty', { waitUntil: 'networkidle', timeout: 30000 }).catch((e) => errs.push('GOTO ' + e.message));
await p.waitForTimeout(1500);
await p.screenshot({ path: 'ui-shots/loyalty_tenant.png', fullPage: true });
console.log('errors:', errs.length ? errs.slice(0, 3) : 'none');
await b.close();
