import type { ResourceConfig } from './resourceTypes';
import { userRoles, announcementAudienceOptions } from './resourceCommon';

export const coreResourceConfigs: Record<string, ResourceConfig> = {
  users: {
    title: 'Users & Akses',
    supportsIsActiveFilter: true,
    path: '/users',
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'fullName', label: 'Nama' },
      { key: 'email', label: 'Email' },
      { key: 'role', label: 'Role' },
      { key: 'tenantId', label: 'Tenant Terkait' },
      { key: 'isActive', label: 'Aktif' },
    ],
    fields: [
      {
        name: 'fullName',
        label: 'Nama Lengkap',
        type: 'text',
        placeholder: 'Nama lengkap user',
        required: true,
      },
      {
        name: 'email',
        label: 'Email',
        type: 'email',
        placeholder: 'email@contoh.com',
        required: true,
      },
      {
        name: 'password',
        label: 'Password',
        type: 'password',
        placeholder: 'Password minimal 8 karakter',
        required: true,
      },
      {
        name: 'role',
        label: 'Role',
        type: 'select',
        options: userRoles,
        required: true,
      },
      {
        name: 'tenantId',
        label: 'Tenant Terkait',
        type: 'select',
        placeholder: 'Pilih tenant bila role = TENANT',
      },
      { name: 'isActive', label: 'Akun Aktif', type: 'checkbox' },
    ],
  },

  tenants: {
    title: 'Tenants & Portal Access',
    supportsIsActiveFilter: true,
    path: '/tenants',
    columns: [
      { key: 'fullName', label: 'Nama Tenant' },
      { key: 'phone', label: 'HP' },
      { key: 'email', label: 'Email' },
      { key: 'portalAccess', label: 'Akses Portal' },
      { key: 'isActive', label: 'Status' },
      { key: 'originCity', label: 'Kota Asal' },
    ],
    fields: [
      {
        name: 'fullName',
        label: 'Nama Lengkap',
        type: 'text',
        placeholder: 'Nama lengkap tenant',
        required: true,
      },
      {
        name: 'phone',
        label: 'No. HP',
        type: 'text',
        placeholder: '08xxxxxxxxxx atau +628xxxxxxxxxx',
        required: true,
      },
      {
        name: 'identityNumber',
        label: 'No. KTP',
        type: 'text',
        placeholder: 'Nomor KTP tenant',
        required: true,
      },
      {
        name: 'emergencyContactName',
        label: 'Nama Kontak Darurat',
        type: 'text',
        placeholder: 'Nama kontak darurat',
      },
      {
        name: 'emergencyContactPhone',
        label: 'Telp Kontak Darurat',
        type: 'text',
        placeholder: 'Nomor telepon kontak darurat',
      },
      {
        name: 'email',
        label: 'Email Tenant (untuk kontak)',
        type: 'email',
        placeholder: 'email@contoh.com',
      },
      {
        name: 'gender',
        label: 'Jenis Kelamin',
        type: 'select',
        options: [
          { value: 'MALE', label: 'Laki-laki' },
          { value: 'FEMALE', label: 'Perempuan' },
          { value: 'OTHER', label: 'Lainnya' },
        ],
      },
      { name: 'birthDate', label: 'Tanggal Lahir', type: 'date' },
      {
        name: 'originCity',
        label: 'Kota Asal',
        type: 'text',
        placeholder: 'Kota asal tenant',
      },
      {
        name: 'occupation',
        label: 'Pekerjaan',
        type: 'text',
        placeholder: 'Pekerjaan tenant',
      },
      {
        name: 'companyOrCampus',
        label: 'Instansi / Kampus',
        type: 'text',
        placeholder: 'Nama perusahaan atau kampus',
      },
      {
        name: 'images',
        label: 'Galeri Gambar',
        type: 'text',
        placeholder: 'Unggah gambar kamar',
      },
      {
        name: 'notes',
        label: 'Catatan',
        type: 'textarea',
        placeholder: 'Catatan tambahan tentang tenant',
      },
      { name: 'isActive', label: 'Tenant Aktif', type: 'checkbox' },
    ],
  },

  rooms: {
    title: 'Rooms',
    supportsIsActiveFilter: true,
    path: '/rooms',
    columns: [
      { key: 'code', label: 'Kamar' },
      { key: 'floor', label: 'Lantai' },
      { key: 'status', label: 'Status Kamar' },
      { key: 'monthlyRateRupiah', label: 'Tarif Bulanan' },
    ],
    fields: [
      {
        name: 'code',
        label: 'Kode Kamar',
        type: 'text',
        placeholder: 'Contoh: A101, B202, C303',
        required: true,
      },
      {
        name: 'name',
        label: 'Nama Kamar',
        type: 'text',
        placeholder: 'Contoh: Kamar Standard Lantai 1, Kamar VIP',
        required: true,
      },
      {
        name: 'floor',
        label: 'Lantai',
        type: 'text',
        placeholder: 'Contoh: 1, 2, 3, Lantai Dasar',
        required: true,
      },
      {
        name: 'monthlyRateRupiah',
        label: 'Tarif Bulanan',
        type: 'currency',
        placeholder: '1500000 untuk Rp 1.500.000',
        required: true,
      },
      {
        name: 'weeklyRateRupiah',
        label: 'Tarif Mingguan',
        type: 'currency',
        placeholder: '400000 untuk Rp 400.000',
        required: true,
      },
      {
        name: 'biWeeklyRateRupiah',
        label: 'Tarif 2 Mingguan',
        type: 'currency',
        placeholder: '750000 untuk Rp 750.000',
        required: true,
      },
      {
        name: 'dailyRateRupiah',
        label: 'Tarif Harian',
        type: 'currency',
        placeholder: '75000 untuk Rp 75.000',
        required: true,
      },
      {
        name: 'defaultDepositRupiah',
        label: 'Deposit Default',
        type: 'currency',
        placeholder: '2000000 untuk Rp 2.000.000',
        required: true,
      },
      {
        name: 'electricityTariffPerKwhRupiah',
        label: 'Tarif Listrik per kWh',
        type: 'currency',
        placeholder: '1500 untuk Rp 1.500 per kWh',
        required: true,
      },
      {
        name: 'waterTariffPerM3Rupiah',
        label: 'Tarif Air per m³',
        type: 'currency',
        placeholder: '8000 untuk Rp 8.000 per m³',
        required: true,
      },
      {
        name: 'images',
        label: 'Galeri Gambar',
        type: 'text',
        placeholder: 'Unggah gambar kamar',
      },
      {
        name: 'notes',
        label: 'Catatan',
        type: 'textarea',
        placeholder: 'Catatan tambahan tentang kamar, fasilitas, kondisi, dll.',
      },
      { name: 'isActive', label: 'Master Data Aktif', type: 'checkbox' },
    ],
  },

  stays: {
    title: 'Hunian & Check-in',
    path: '/stays',
    createLabel: 'Check-in Baru',
    columns: [
      { key: 'id', label: 'Stay' },
      { key: 'checkInDate', label: 'Check-in' },
      { key: 'status', label: 'Status' },
      { key: 'agreedRentAmountRupiah', label: 'Sewa' },
    ],
    fields: [
      {
        name: 'tenantId',
        label: 'Tenant',
        type: 'number',
        placeholder: 'Pilih tenant',
        required: true,
      },
      {
        name: 'roomId',
        label: 'Kamar',
        type: 'number',
        placeholder: 'Pilih kamar',
        required: true,
      },
      {
        name: 'pricingTerm',
        label: 'Termin Sewa',
        type: 'select',
        options: [
          { value: 'MONTHLY', label: 'Bulanan' },
          { value: 'WEEKLY', label: 'Mingguan' },
          { value: 'DAILY', label: 'Harian' },
          { value: 'BIWEEKLY', label: '2 Mingguan' },
          { value: 'SMESTERLY', label: 'Semesteran' },
          { value: 'YEARLY', label: 'Tahunan' },
        ],
        required: true,
      },
      {
        name: 'checkInDate',
        label: 'Tanggal Check-in',
        type: 'date',
        placeholder: 'Tanggal check-in',
        required: true,
      },
      {
        name: 'agreedRentAmountRupiah',
        label: 'Sewa Disepakati',
        type: 'currency',
        placeholder: 'Jumlah sewa yang disepakati dalam Rupiah',
        required: true,
      },
      {
        name: 'depositAmountRupiah',
        label: 'Deposit',
        type: 'currency',
        placeholder: 'Jumlah deposit dalam Rupiah',
      },
      {
        name: 'stayPurpose',
        label: 'Tujuan Tinggal',
        type: 'select',
        options: [
          { value: 'WORK', label: 'Kerja' },
          { value: 'STUDY', label: 'Kuliah' },
          { value: 'TRANSIT', label: 'Transit' },
          { value: 'FAMILY', label: 'Keluarga' },
          { value: 'MEDICAL', label: 'Medis' },
          { value: 'PROJECT', label: 'Proyek' },
          { value: 'OTHER', label: 'Lainnya' },
        ],
        placeholder: 'Pilih tujuan tinggal',
      },
      {
        name: 'bookingSource',
        label: 'Sumber Booking',
        type: 'select',
        options: [
          { value: 'GOOGLE_MAPS', label: 'Google Maps' },
          { value: 'WALK_IN', label: 'Datang Langsung' },
          { value: 'REFERRAL', label: 'Referensi' },
          { value: 'INSTAGRAM', label: 'Instagram' },
          { value: 'TIKTOK', label: 'TikTok' },
          { value: 'WHATSAPP', label: 'WhatsApp' },
          { value: 'FACEBOOK', label: 'Facebook' },
          { value: 'WEBSITE', label: 'Website' },
          { value: 'OTA', label: 'OTA (Online Travel Agent)' },
          { value: 'OTHER', label: 'Lainnya' },
        ],
        placeholder: 'Pilih sumber booking',
      },
      {
        name: 'images',
        label: 'Galeri Gambar',
        type: 'text',
        placeholder: 'Unggah gambar kamar',
      },
      {
        name: 'notes',
        label: 'Catatan',
        type: 'textarea',
        placeholder: 'Catatan tambahan tentang stay',
      },
    ],
  },

};
