import type { ResourceConfig } from './resourceTypes';
import { userRoles, announcementAudienceOptions } from './resourceCommon';

export const financeResourceConfigs: Record<string, ResourceConfig> = {
  'inventory-movements': {
    title: 'Histori Pergerakan Stok',
    path: '/inventory-movements',
    createLabel: 'Catat Pergerakan Stok',
    columns: [
      { key: 'itemId', label: 'Barang' },
      { key: 'movementType', label: 'Tipe' },
      { key: 'qty', label: 'Qty' },
      { key: 'roomId', label: 'Kamar' },
      { key: 'movementDate', label: 'Tanggal' },
    ],
    fields: [
      {
        name: 'itemId',
        label: 'Barang',
        type: 'number',
        placeholder: 'Pilih barang',
        required: true,
      },
      {
        name: 'movementType',
        label: 'Tipe Pergerakan',
        type: 'select',
        options: [
          { value: 'IN', label: 'Barang Masuk' },
          { value: 'OUT', label: 'Barang Keluar' },
          { value: 'ASSIGN_TO_ROOM', label: 'Pasang ke Kamar' },
          { value: 'RETURN_FROM_ROOM', label: 'Kembali dari Kamar' },
        ],
        required: true,
      },
      {
        name: 'qty',
        label: 'Qty',
        type: 'text',
        placeholder: 'Jumlah barang',
        required: true,
      },
      {
        name: 'roomId',
        label: 'Kamar Terkait',
        type: 'number',
        placeholder: 'Pilih kamar bila applicable',
      },
      {
        name: 'movementDate',
        label: 'Tanggal',
        type: 'date',
        placeholder: 'Tanggal pergerakan',
        required: true,
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea',
        placeholder: 'Catatan pergerakan barang',
      },
    ],
  },

  'wifi-sales': {
    title: 'Penjualan Voucher WiFi',
    path: '/wifi-sales',
    allowDelete: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'saleDate', label: 'Tanggal' },
      { key: 'customerName', label: 'Pembeli / Tenant' },
      { key: 'packageName', label: 'Paket Voucher' },
      { key: 'soldPriceRupiah', label: 'Nominal' },
    ],
    fields: [
      {
        name: 'saleDate',
        label: 'Tanggal',
        type: 'date',
        placeholder: 'Tanggal penjualan',
        required: true,
      },
      {
        name: 'customerName',
        label: 'Nama Pembeli / Tenant',
        type: 'text',
        placeholder: 'Nama tenant, tamu, atau pembeli voucher',
        required: true,
      },
      {
        name: 'packageName',
        label: 'Paket Voucher WiFi',
        type: 'text',
        placeholder: 'Contoh: Harian 10 Mbps, Mingguan, Bulanan',
        required: true,
      },
      {
        name: 'soldPriceRupiah',
        label: 'Nominal Penjualan',
        type: 'currency',
        placeholder: 'Nominal voucher WiFi yang dibayar',
        required: true,
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea',
        placeholder: 'Catatan penjualan',
      },
    ],
  },

  expenses: {
    title: 'Pengeluaran Operasional',
    supportsIsActiveFilter: true,
    path: '/expenses',
    allowDelete: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'expenseDate', label: 'Tanggal' },
      { key: 'type', label: 'Tipe' },
      { key: 'category', label: 'Kategori' },
      { key: 'description', label: 'Deskripsi' },
      { key: 'amountRupiah', label: 'Nominal' },
    ],
    fields: [
      {
        name: 'expenseDate',
        label: 'Tanggal',
        type: 'date',
        placeholder: 'Tanggal pengeluaran',
        required: true,
      },
      {
        name: 'type',
        label: 'Tipe',
        type: 'select',
        options: [
          { value: 'FIXED', label: 'Tetap' },
          { value: 'VARIABLE', label: 'Variabel' },
        ],
        required: true,
      },
      {
        name: 'category',
        label: 'Kategori',
        type: 'select',
        options: [
          { value: 'RENT_BUILDING', label: 'Sewa Gedung / Tanah' },
          { value: 'SALARY', label: 'Gaji Staff / Operasional Orang' },
          { value: 'ELECTRICITY', label: 'Listrik PLN' },
          { value: 'WATER', label: 'Air / PDAM / Pompa' },
          { value: 'INTERNET', label: 'Internet / ISP / Modal WiFi' },
          { value: 'MAINTENANCE', label: 'Maintenance / Perbaikan / Pest Control' },
          { value: 'CLEANING', label: 'Kebersihan / Laundry Partner / Jasa Bersih' },
          { value: 'SUPPLIES', label: 'Supplies / Galon / Inventaris Kecil' },
          { value: 'TAX', label: 'Pajak / Retribusi / Sampah' },
          { value: 'MARKETING', label: 'Marketing / Listing / Komisi Platform' },
          { value: 'OTHER', label: 'Lainnya / Bank Fee / Software / CCTV' },
        ],
        required: true,
      },
      {
        name: 'description',
        label: 'Deskripsi',
        type: 'text',
        placeholder: 'Deskripsi pengeluaran',
        required: true,
      },
      {
        name: 'amountRupiah',
        label: 'Nominal',
        type: 'currency',
        placeholder: 'Jumlah pengeluaran dalam Rupiah',
        required: true,
      },
      {
        name: 'vendorName',
        label: 'Vendor',
        type: 'text',
        placeholder: 'Nama vendor',
      },
      {
        name: 'roomId',
        label: 'Kamar Terkait',
        type: 'number',
        placeholder: 'Pilih kamar bila applicable',
      },
      {
        name: 'stayId',
        label: 'Stay Terkait',
        type: 'number',
        placeholder: 'Pilih stay bila applicable',
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea',
        placeholder: 'Catatan pengeluaran',
      },
    ],
  },
};
