export const financeConfigs = {
  'invoice-payments': {
    title: 'Invoice Payments',
    path: '/invoice-payments',
    emptyMessage: 'Belum ada pembayaran invoice tercatat. Klik "Tambah" untuk mencatat pembayaran pertama.',
    allowDelete: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'invoiceId', label: 'Invoice' },
      { key: 'paymentDate', label: 'Tanggal' },
      { key: 'amountRupiah', label: 'Nominal' },
      { key: 'method', label: 'Metode' },
    ],
    fields: [
      {
        name: 'invoiceId',
        label: 'Invoice',
        type: 'number' as const,
        placeholder: 'Pilih invoice',
        required: true,
      },
      {
        name: 'paymentDate',
        label: 'Tanggal Pembayaran',
        type: 'date' as const,
        placeholder: 'Tanggal pembayaran',
        required: true,
      },
      {
        name: 'amountRupiah',
        label: 'Nominal',
        type: 'currency' as const,
        placeholder: 'Jumlah pembayaran dalam Rupiah',
        required: true,
      },
      {
        name: 'method',
        label: 'Metode',
        type: 'select' as const,
        options: [
          { value: 'CASH', label: 'Tunai' },
          { value: 'TRANSFER', label: 'Transfer' },
          { value: 'QRIS', label: 'QRIS' },
          { value: 'EWALLET', label: 'E-Wallet' },
          { value: 'OTHER', label: 'Lainnya' },
        ],
        required: true,
      },
      {
        name: 'referenceNo',
        label: 'Nomor Referensi',
        type: 'text' as const,
        placeholder: 'Nomor referensi pembayaran',
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan pembayaran',
      },
    ],
  },

  'wifi-sales': {
    title: 'Penjualan Voucher WiFi',
    path: '/wifi-sales',
    emptyMessage: 'Belum ada penjualan voucher WiFi. Klik "Tambah" untuk mencatat penjualan pertama.',
    allowDelete: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'saleDate', label: 'Tanggal' },
      { key: 'customerName', label: 'Pembeli / Tenant' },
      { key: 'packageName', label: 'Paket Voucher' },
      { key: 'soldPriceRupiah', label: 'Nominal' },
    ],
    fields: [
      {
        name: 'saleDate',
        label: 'Tanggal',
        type: 'date' as const,
        placeholder: 'Tanggal penjualan',
        required: true,
      },
      {
        name: 'customerName',
        label: 'Nama Pembeli / Tenant',
        type: 'text' as const,
        placeholder: 'Nama tenant, tamu, atau pembeli voucher',
        required: true,
      },
      {
        name: 'packageName',
        label: 'Paket Voucher WiFi',
        type: 'text' as const,
        placeholder: 'Contoh: Harian 10 Mbps, Mingguan, Bulanan',
        required: true,
      },
      {
        name: 'soldPriceRupiah',
        label: 'Nominal Penjualan',
        type: 'currency' as const,
        placeholder: 'Nominal voucher WiFi yang dibayar',
        required: true,
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan penjualan',
      },
    ],
  },

  expenses: {
    title: 'Pengeluaran Operasional',
    supportsIsActiveFilter: true,
    path: '/expenses',
    emptyMessage: 'Belum ada pengeluaran tercatat. Klik "Tambah" untuk mencatat pengeluaran operasional pertama.',
    allowDelete: true,
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'expenseDate', label: 'Tanggal' },
      { key: 'type', label: 'Tipe' },
      { key: 'status', label: 'Status' },
      { key: 'category', label: 'Kategori' },
      { key: 'description', label: 'Deskripsi' },
      { key: 'amountRupiah', label: 'Nominal' },
    ],
    fields: [
      {
        name: 'expenseDate',
        label: 'Tanggal',
        type: 'date' as const,
        placeholder: 'Tanggal pengeluaran',
        required: true,
      },
      {
        name: 'type',
        label: 'Tipe',
        type: 'select' as const,
        options: [
          { value: 'FIXED', label: 'Tetap' },
          { value: 'VARIABLE', label: 'Variabel' },
        ],
        required: true,
      },
      {
        name: 'status',
        label: 'Status Draft',
        type: 'select' as const,
        options: [
          { value: 'DRAFT', label: 'Draft - perlu konfirmasi' },
          { value: 'CONFIRMED', label: 'Confirmed - posting jurnal' },
          { value: 'CANCELLED', label: 'Dibatalkan' },
        ],
      },
      {
        name: 'category',
        label: 'Kategori',
        type: 'select' as const,
        options: [
          { value: 'RENT_BUILDING', label: 'Sewa Gedung / Tanah' },
          { value: 'SALARY', label: 'Gaji Staff / Operasional Orang' },
          { value: 'ELECTRICITY', label: 'Listrik PLN' },
          { value: 'WATER', label: 'Air / PDAM / Pompa' },
          { value: 'INTERNET', label: 'Internet / ISP / Modal WiFi' },
          { value: 'MAINTENANCE', label: 'Perawatan / Perbaikan / Pest Control' },
          { value: 'CLEANING', label: 'Kebersihan / Laundry Partner / Jasa Bersih' },
          { value: 'SUPPLIES', label: 'Supplies / Galon / Inventaris Kecil' },
          { value: 'TAX', label: 'Pajak / Retribusi / Sampah' },
          { value: 'MARKETING', label: 'Marketing / Listing / Komisi Platform' },
          { value: 'OTHER', label: 'Lainnya / Bank Fee / Software / CCTV' },
        ],
        required: true,
      },
      {
        name: 'description',
        label: 'Deskripsi',
        type: 'text' as const,
        placeholder: 'Deskripsi pengeluaran',
        required: true,
      },
      {
        name: 'amountRupiah',
        label: 'Nominal',
        type: 'currency' as const,
        placeholder: 'Jumlah pengeluaran dalam Rupiah',
        required: true,
      },
      {
        name: 'vendorName',
        label: 'Vendor',
        type: 'text' as const,
        placeholder: 'Nama vendor',
      },
      {
        name: 'roomId',
        label: 'Kamar Terkait',
        type: 'number' as const,
        placeholder: 'Pilih kamar bila applicable',
      },
      {
        name: 'stayId',
        label: 'Masa Sewa Terkait',
        type: 'number' as const,
        placeholder: 'Pilih stay bila applicable',
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan pengeluaran',
      },
    ],
  },
};
