export const inventoryConfigs = {
  'inventory-items': {
    title: 'Stok Barang',
    path: '/inventory-items',
    emptyMessage: "Belum ada barang di gudang. Klik 'Tambah' untuk mencatat barang pertama.",
    columns: [
      { key: 'id', label: 'ID' },
      { key: 'sku', label: 'SKU' },
      { key: 'name', label: 'Nama' },
      { key: 'category', label: 'Kategori' },
      { key: 'qtyOnHand', label: 'Stok Gudang' },
      { key: 'positionSummary', label: 'Posisi' },
      { key: 'minQty', label: 'Min Stok' },
      { key: 'status', label: 'Kondisi' },
    ],
    fields: [
      {
        name: 'sku',
        label: 'SKU',
        type: 'text' as const,
        placeholder: 'Kode SKU barang',
        required: true,
      },
      {
        name: 'name',
        label: 'Nama Barang',
        type: 'text' as const,
        placeholder: 'Nama barang',
        required: true,
      },
      {
        name: 'category',
        label: 'Kategori',
        type: 'text' as const,
        placeholder: 'Kategori barang',
        required: true,
      },
      {
        name: 'unit',
        label: 'Satuan',
        type: 'text' as const,
        placeholder: 'pcs, unit, liter, set, dll',
        required: true,
      },
      {
        name: 'qtyOnHand',
        label: 'Stok Awal / Saat Ini',
        type: 'text' as const,
        placeholder: 'Isi saat tambah barang. Edit stok lewat Mutasi Stok.',
        required: true,
      },
      {
        name: 'minQty',
        label: 'Batas Minimum',
        type: 'text' as const,
        placeholder: 'Jumlah minimum stok',
      },
      {
        name: 'status',
        label: 'Status Barang',
        type: 'select' as const,
        options: [
          { value: 'GOOD', label: 'Baik' },
          { value: 'DAMAGED', label: 'Rusak' },
          { value: 'MISSING', label: 'Hilang' },
          { value: 'NEEDS_REPAIR', label: 'Perlu Diperbaiki' },
        ],
      },
      {
        name: 'notes',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan tambahan tentang barang',
      },
      { name: 'isActive', label: 'Barang Aktif', type: 'checkbox' as const },
    ],
  },

  'room-items': {
    title: 'Barang di Kamar',
    path: '/room-items',
    createLabel: 'Lewat Mutasi Stok',
    emptyMessage: 'Belum ada barang tercatat di kamar. Tugaskan barang dari Gudang via tab Mutasi.',
    columns: [
      { key: 'roomId', label: 'Kamar' },
      { key: 'itemId', label: 'Barang' },
      { key: 'qty', label: 'Jumlah' },
      { key: 'status', label: 'Kondisi' },
    ],
    fields: [
      {
        name: 'roomId',
        label: 'Kamar',
        type: 'number' as const,
        placeholder: 'Pilih kamar',
        required: true,
      },
      {
        name: 'itemId',
        label: 'Barang',
        type: 'number' as const,
        placeholder: 'Pilih barang',
        required: true,
      },
      {
        name: 'qty',
        label: 'Jumlah',
        type: 'text' as const,
        placeholder: 'Jumlah barang',
        required: true,
      },
      {
        name: 'status',
        label: 'Status',
        type: 'select' as const,
        options: [
          { value: 'GOOD', label: 'Baik' },
          { value: 'DAMAGED', label: 'Rusak' },
          { value: 'MAINTENANCE', label: 'Perlu Dicek' },
          { value: 'MISSING', label: 'Hilang' },
        ],
        required: true,
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan kondisi barang',
      },
    ],
  },

  'inventory-movements': {
    title: 'Mutasi Stok Resmi',
    path: '/inventory-movements',
    createLabel: 'Catat Mutasi',
    emptyMessage: 'Belum ada mutasi. Mulai dengan menugaskan barang dari Gudang ke kamar.',
    columns: [
      { key: 'itemId', label: 'Barang' },
      { key: 'movementType', label: 'Jenis' },
      { key: 'qty', label: 'Jumlah' },
      { key: 'roomId', label: 'Kamar' },
      { key: 'movementDate', label: 'Tanggal' },
    ],
    fields: [
      {
        name: 'itemId',
        label: 'Barang',
        type: 'number' as const,
        placeholder: 'Pilih barang',
        required: true,
      },
      {
        name: 'movementType',
        label: 'Jenis Mutasi',
        type: 'select' as const,
        options: [
          { value: 'IN', label: 'Barang Masuk' },
          { value: 'OUT', label: 'Barang Keluar' },
          { value: 'ASSIGN_TO_ROOM', label: 'Pasang ke Kamar' },
          { value: 'RETURN_FROM_ROOM', label: 'Kembali dari Kamar' },
        ],
        required: true,
      },
      {
        name: 'qty',
        label: 'Qty',
        type: 'text' as const,
        placeholder: 'Jumlah barang',
        required: true,
      },
      {
        name: 'roomId',
        label: 'Kamar Terkait',
        type: 'number' as const,
        placeholder: 'Pilih kamar bila applicable',
      },
      {
        name: 'movementDate',
        label: 'Tanggal',
        type: 'date' as const,
        placeholder: 'Tanggal pergerakan',
        required: true,
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Alasan mutasi, contoh: lampu rusak diganti / stok galon masuk',
        required: true,
      },
    ],
  },
};
