export const propertyConfigs = {
  rooms: {
    title: 'Kamar & Stok',
    supportsIsActiveFilter: true,
    path: '/rooms',
    columns: [
      { key: 'code', label: 'Kamar' },
      { key: 'floor', label: 'Lantai' },
      { key: 'category', label: 'Kategori' },
      { key: 'roomSize', label: 'Ukuran' },
      { key: 'status', label: 'Status Kamar' },
      { key: 'monthlyRateRupiah', label: 'Tarif Bulanan' },
    ],
    fields: [
      {
        name: 'code',
        label: 'Kode Kamar',
        type: 'text' as const,
        placeholder: 'Contoh: A101, B202, C303',
        required: true,
      },
      {
        name: 'name',
        label: 'Nama Kamar',
        type: 'text' as const,
        placeholder: 'Contoh: Kamar Standard Lantai 1, Kamar VIP',
        required: true,
      },
      {
        name: 'floor',
        label: 'Lantai',
        type: 'text' as const,
        placeholder: 'Contoh: 1, 2, 3, Lantai Dasar',
        required: true,
      },
      {
        name: 'category',
        label: 'Kategori Kamar',
        type: 'select' as const,
        options: [
          { value: 'STANDARD', label: 'Standar' },
          { value: 'ECONOMY', label: 'Ekonomi' },
          { value: 'DELUXE', label: 'Deluxe' },
        ],
      },
      {
        name: 'roomType',
        label: 'Tipe Kamar',
        type: 'select' as const,
        options: [
          { value: 'REGULAR', label: 'Reguler' },
          { value: 'MEZZANINE', label: 'Mezzanine' },
        ],
      },
      {
        name: 'roomSize',
        label: 'Ukuran Kamar',
        type: 'select' as const,
        options: [
          { value: 'STANDARD', label: 'Standar 2,5×3m (~7,5m², maks 2 org)' },
          { value: 'LARGE', label: 'Besar 3×3,5m (~10,5m², maks 4 org, +Rp 200rb/bln)' },
        ],
      },
      {
        name: 'monthlyRateRupiah',
        label: 'Tarif Bulanan',
        type: 'currency' as const,
        placeholder: '1500000 untuk Rp 1.500.000',
        required: true,
      },
      {
        name: 'weeklyRateRupiah',
        label: 'Tarif Mingguan',
        type: 'currency' as const,
        placeholder: '400000 untuk Rp 400.000',
        required: true,
      },
      {
        name: 'biWeeklyRateRupiah',
        label: 'Tarif 2 Mingguan',
        type: 'currency' as const,
        placeholder: '750000 untuk Rp 750.000',
        required: true,
      },
      {
        name: 'dailyRateRupiah',
        label: 'Tarif Harian',
        type: 'currency' as const,
        placeholder: '75000 untuk Rp 75.000',
        required: true,
      },
      {
        name: 'defaultDepositRupiah',
        label: 'Deposit Default',
        type: 'currency' as const,
        placeholder: '2000000 untuk Rp 2.000.000',
        required: true,
      },
      {
        name: 'electricityTariffPerKwhRupiah',
        label: 'Tarif Listrik per kWh',
        type: 'currency' as const,
        placeholder: '1500 untuk Rp 1.500 per kWh',
        required: true,
      },
      {
        name: 'waterTariffPerM3Rupiah',
        label: 'Tarif Air per m³',
        type: 'currency' as const,
        placeholder: '8000 untuk Rp 8.000 per m³',
        required: true,
      },
      {
        name: 'hasAc',
        label: 'Ada AC',
        type: 'checkbox' as const,
      },
      {
        name: 'acWattage',
        label: 'Daya AC (watt)',
        type: 'number' as const,
        placeholder: 'mis. 400 (AC 1/2 PK ~ 380-450 watt)',
      },
      {
        name: 'acCleanIntervalDays',
        label: 'Interval Cuci AC (hari)',
        type: 'number' as const,
        placeholder: 'Default 90 hari',
      },
      {
        name: 'acUsageHoursPerDay',
        label: 'Estimasi Jam Pakai AC / hari',
        type: 'number' as const,
        placeholder: 'mis. 8 (untuk pemicu dini cuci AC berbasis kWh)',
      },
      {
        name: 'images',
        label: 'Foto Kamar',
        type: 'textarea' as const,
        placeholder: 'Unggah foto kamar. Foto pertama menjadi cover utama di katalog.',
      },
      {
        name: 'notes',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan tambahan tentang kamar, fasilitas, kondisi, dll.',
      },
      { name: 'isActive', label: 'Master Data Aktif', type: 'checkbox' as const },
    ],
  },

  stays: {
    title: 'Hunian & Check-in',
    path: '/stays',
    createLabel: 'Check-in Baru',
    columns: [
      { key: 'id', label: 'Masa Sewa' },
      { key: 'checkInDate', label: 'Check-in' },
      { key: 'status', label: 'Status' },
      { key: 'agreedRentAmountRupiah', label: 'Sewa' },
    ],
    fields: [
      {
        name: 'tenantId',
        label: 'Tenant',
        type: 'number' as const,
        placeholder: 'Pilih tenant',
        required: true,
      },
      {
        name: 'roomId',
        label: 'Kamar',
        type: 'number' as const,
        placeholder: 'Pilih kamar',
        required: true,
      },
      {
        name: 'pricingTerm',
        label: 'Termin Sewa',
        type: 'select' as const,
        options: [
          { value: 'MONTHLY', label: 'Bulanan' },
          { value: 'WEEKLY', label: 'Mingguan' },
          { value: 'DAILY', label: 'Harian' },
          { value: 'BIWEEKLY', label: '2 Mingguan' },
          { value: 'SMESTERLY', label: 'Semesteran' },
          { value: 'YEARLY', label: 'Tahunan' },
        ],
        required: true,
      },
      {
        name: 'checkInDate',
        label: 'Tanggal Check-in',
        type: 'date' as const,
        placeholder: 'Tanggal check-in',
        required: true,
      },
      {
        name: 'agreedRentAmountRupiah',
        label: 'Sewa Disepakati',
        type: 'currency' as const,
        placeholder: 'Jumlah sewa yang disepakati dalam Rupiah',
        required: true,
      },
      {
        name: 'depositAmountRupiah',
        label: 'Deposit',
        type: 'currency' as const,
        placeholder: 'Jumlah deposit dalam Rupiah',
      },
      {
        name: 'stayPurpose',
        label: 'Tujuan Tinggal',
        type: 'select' as const,
        options: [
          { value: 'WORK', label: 'Kerja' },
          { value: 'STUDY', label: 'Kuliah' },
          { value: 'TRANSIT', label: 'Transit' },
          { value: 'FAMILY', label: 'Keluarga' },
          { value: 'MEDICAL', label: 'Medis' },
          { value: 'PROJECT', label: 'Proyek' },
          { value: 'OTHER', label: 'Lainnya' },
        ],
        placeholder: 'Pilih tujuan tinggal',
      },
      {
        name: 'bookingSource',
        label: 'Sumber Booking',
        type: 'select' as const,
        options: [
          { value: 'GOOGLE_MAPS', label: 'Google Maps' },
          { value: 'WALK_IN', label: 'Datang Langsung' },
          { value: 'REFERRAL', label: 'Referensi' },
          { value: 'INSTAGRAM', label: 'Instagram' },
          { value: 'TIKTOK', label: 'TikTok' },
          { value: 'WHATSAPP', label: 'WhatsApp' },
          { value: 'FACEBOOK', label: 'Facebook' },
          { value: 'WEBSITE', label: 'Website' },
          { value: 'OTA', label: 'OTA (Online Travel Agent)' },
          { value: 'OTHER', label: 'Lainnya' },
        ],
        placeholder: 'Pilih sumber booking',
      },
      {
        name: 'notes',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan tambahan tentang stay',
      },
    ],
  },

  'meter-readings': {
    title: 'Riwayat Meter & Input Manual',
    path: '/meter-readings',
    createLabel: 'Catat Meter Manual',
    columns: [
      { key: 'roomId', label: 'Kamar' },
      { key: 'utilityType', label: 'Utilitas' },
      { key: 'readingAt', label: 'Tanggal' },
      { key: 'readingValue', label: 'Nilai' },
    ],
    fields: [
      {
        name: 'roomId',
        label: 'Kamar',
        type: 'number' as const,
        placeholder: 'Pilih kamar',
        required: true,
      },
      {
        name: 'utilityType',
        label: 'Utilitas',
        type: 'select' as const,
        options: [
          { value: 'ELECTRICITY', label: 'Listrik' },
          { value: 'WATER', label: 'Air' },
        ],
        required: true,
      },
      {
        name: 'readingAt',
        label: 'Tanggal',
        type: 'date' as const,
        placeholder: 'Tanggal pembacaan meter',
        required: true,
      },
      {
        name: 'readingValue',
        label: 'Nilai Meter',
        type: 'text' as const,
        placeholder: 'Nilai meter (angka)',
        required: true,
      },
      {
        name: 'note',
        label: 'Catatan',
        type: 'textarea' as const,
        placeholder: 'Catatan tambahan',
      },
    ],
  },

  // PUB-LAYANAN-TAMBAHAN: layanan tambahan + tarif yang dikelola owner.
  additionalServices: {
    title: 'Layanan Tambahan',
    path: '/additional-services',
    allowDelete: true,
    supportsIsActiveFilter: true,
    columns: [
      { key: 'sortOrder', label: 'Urutan' },
      { key: 'name', label: 'Layanan' },
      { key: 'priceRupiah', label: 'Tarif' },
      { key: 'unit', label: 'Satuan' },
      { key: 'isActive', label: 'Aktif' },
    ],
    fields: [
      { name: 'name', label: 'Nama Layanan', type: 'text' as const, placeholder: 'Contoh: Galon Air, TV Tambahan', required: true },
      { name: 'description', label: 'Deskripsi', type: 'textarea' as const, placeholder: 'Penjelasan singkat (opsional)' },
      { name: 'priceRupiah', label: 'Tarif', type: 'currency' as const, placeholder: '15000 untuk Rp 15.000', required: true },
      { name: 'unit', label: 'Satuan', type: 'text' as const, placeholder: 'Contoh: per galon, per bulan, per unit' },
      { name: 'sortOrder', label: 'Urutan Tampil', type: 'number' as const, placeholder: '0' },
      { name: 'isActive', label: 'Aktif (tampil ke penghuni)', type: 'checkbox' as const },
    ],
  },
};
